### ISSUE TITLE
Increase 48 hour availability

### ISSUE THREAD

**Issue by gcleaves** [Runscope/requestbin#57]
Hello. Thanks for making this code publicly available. How can I go about making a bin available for more than 48 hours?

Cheers.

**Comment by ericluria** [comment]
You'll need to set this environment variable: https://github.com/Runscope/requestbin/blob/5cc985bce4ba50ba2df902aff2871ba812a438b4/requestbin/config.py#L14

Found it by searching the code for `48` :)

**Comment by nemathew** [comment]
I was able to find this line in the code. I'm brand new to web services and I'm still trying to learn how all of this works. Will changing this alone make it so that the bins last longer or do you need to get a new URL as well?

**Comment by ericluria** [comment]
@nemathew what do you mean by "get a new URL"? If you mean a new Heroku instance, you'll be fine by running `heroku config:set "BIN_TTL=7*24*3600"` from the command line since it restarts the instance and keeps the same URL.

If you mean a new URL as in a new request bin, I assume all future bins will respect the new setting after the instance restarts and uses the new configuration.

Hope that helps!

**Comment by nemathew** [comment]
@ericluria That's perfect. Thank you so much for the help! :D

**Comment by tuck1s** [comment]
I have a PR coming for this, that exposes the variable in `app.json` - which means you can edit it directly as part of the "Deploy to Heroku" purple button method.

**Comment by sexygeoff** [comment]
Setting the BIN_TTL variable in docker-compose.yml doesn't have any effect. Any ideas on how to get this to work?

```
app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
        BIN_TTL: 10368000
    links:
        - redis
    ports:
        - "8000:8000"

redis:
    image: redis
```
